"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const _Async = require("./Async");
const _Bools = require("./Bools");
const _Clipboard = require("./Clipboard");
const _Colors = require("./Colors");
const _Dates = require("./Dates");
const _Device = require("./Device");
const _Documents = require("./Documents");
const _Events = require("./Events");
const _Files = require("./Files");
const _Keyboard = require("./Keyboard");
const _Maths = require("./Maths");
const _Measurements = require("./Measurements");
const _Numbers = require("./Numbers");
const _Objects = require("./Objects");
const _Storage = require("./Storage");
const _StorageItem = require("./StorageItem");
const _StorageType = require("./StorageType");
const _Strings = require("./Strings");
const _Urls = require("./Urls");
var Utils;
(function (Utils) {
    Utils.Async = _Async;
    Utils.Bools = _Bools;
    Utils.Clipboard = _Clipboard;
    Utils.Colors = _Colors;
    Utils.Dates = _Dates;
    Utils.Device = _Device;
    Utils.Documents = _Documents;
    Utils.Events = _Events;
    Utils.Files = _Files;
    Utils.Keyboard = _Keyboard;
    Utils.Maths = _Maths;
    Utils.Measurements = _Measurements;
    Utils.Numbers = _Numbers;
    Utils.Objects = _Objects;
    Utils.Storage = _Storage;
    Utils.StorageItem = _StorageItem;
    Utils.StorageType = _StorageType;
    Utils.Strings = _Strings;
    Utils.Urls = _Urls;
})(Utils = exports.Utils || (exports.Utils = {}));
